{
 "title": "hlf-parser",
 "tags": [ "core" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\".*.hlfparser.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heartbeat epoch",
   "type": "stat",
   "description": "Heartbeat epoch of hlfparser",
   "gridPos": { "h": 8, "w": 8, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_heartbeat_epoch{instance=\"$instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Reconnect to HLF event service",
   "type": "bargauge",
   "description": "Count of reconnect to hlf event service",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_event_reconnect_count{instance=\"$instance\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "Quantification of blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blockchain height",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_blockchain_hieght{instance=\"$instance\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Last DB block ",
   "type": "bargauge",
   "description": "Number of last block from database",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_last_block_number{instance=\"$instance\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Count DB block",
   "type": "bargauge",
   "description": "Count of read block from the hlf channel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_number_block{instance=\"$instance\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "Data load parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Block in queue to DB write",
   "type": "bargauge",
   "description": "Number of block in queue to database write",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hlfparser_in_queue_number{instance=\"$instance\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Rate of writing blocks to the database",
   "type": "timeseries",
   "description": "Count of stored to database blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(hlfparser_stored_block_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Rate of reading blocks from the ledger",
   "type": "timeseries",
   "description": "Count of read block from the hlf channel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(hlfparser_read_block_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Block processing rate",
   "type": "timeseries",
   "description": "Count of parsered block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(hlfparser_parsered_block_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{channel}}"
    }
   ]
  }
 ]
}