{
 "title": "api-service",
 "tags": [ "core" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\".*.apiservice.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GoVersion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "GoRoutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "GoThreads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "alloc_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "heap_inuse_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "mspan_inuse_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "gc_sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "heap_alloc_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "mcache_inuse_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "heap_idle_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "frees_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{instance=\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "heap_objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "mcache_sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "alloc_bytes_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "next_gc_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "go_gc_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds{quantile=\"0\",instance=\"$instance\"}[$__interval]))",
     "legendFormat": "quantile=\"0\""
    },
    {
     "expr": "sum(rate(go_gc_duration_seconds{quantile=\"0.25\",instance=\"$instance\"}[$__interval]))",
     "legendFormat": "quantile=\"0.25\""
    },
    {
     "expr": "sum(rate(go_gc_duration_seconds{quantile=\"0.5\",instance=\"$instance\"}[$__interval]))",
     "legendFormat": "quantile=\"0.5\""
    },
    {
     "expr": "sum(rate(go_gc_duration_seconds{quantile=\"0.75\",instance=\"$instance\"}[$__interval]))",
     "legendFormat": "quantile=\"0.75\""
    },
    {
     "expr": "sum(rate(go_gc_duration_seconds{quantile=\"1\",instance=\"$instance\"}[$__interval]))",
     "legendFormat": "quantile=\"1\""
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=\"$instance\"}[$__interval])\n/\nrate(go_gc_duration_seconds_count{instance=\"$instance\"}[$__interval])",
     "legendFormat": "seconds_sum/count"
    }
   ]
  },
  {
   "title": "heap_released_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "other_sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "hash_sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "heap_sys_bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}"
    }
   ]
  }
 ]
}