{
 "title": "hlf",
 "description": "n-t.io version",
 "tags": [ "atomyze" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Hyperledger Fabric Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Version",
   "type": "stat",
   "description": "The active version of Fabric.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_version{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "description": "The active version of Go.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "go_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "stat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ledger_transaction_count{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Requests",
   "type": "stat",
   "description": "The number of proposals received.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "endorser_proposals_received{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Successful",
   "type": "stat",
   "description": "The number of successful proposals. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "endorser_successful_proposals{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "graph",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_blockchain_height{instance=\"$instance\"}",
     "legendFormat": "{{job}}:{{channel}}"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Orderer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(broadcast_validate_duration_count{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(ledger_transaction_count{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Go Memory Allocations",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_heap_objects{instance=\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Garbage Collection",
   "type": "graph",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  },
  {
   "title": "Go Free Memory",
   "type": "graph",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Ledger Block Processing Time",
   "type": "graph",
   "description": "Time taken in seconds for ledger block processing.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_block_processing_time_bucket{instance=\"$instance\"}[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "graph",
   "description": "Time taken in seconds for committing block changes to state db.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_statedb_commit_time_bucket{instance=\"$instance\"}[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Orderer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Orderer Broadcasts",
   "type": "table-old",
   "description": "The number of transactions processed.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "broadcast_processed_count{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Chaincode Shim Requests",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received{instance=\"$instance\"}[5m])",
     "legendFormat": "{{channel}}, {{Received}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed{instance=\"$instance\"}[5m])",
     "legendFormat": "{{channel}}, {{Completed}},  {{chaincode}}, {{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket{instance=\"$instance\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "description": "broadcast_enqueue_duration_sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{channel}}, {{job}}"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed{instance=\"$instance\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Chaincode Launch Duration",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chaincode_launch_duration_count{instance=\"$instance\"}",
     "legendFormat": "{{Count}}, {{chaincode}}"
    },
    {
     "expr": "chaincode_launch_duration_sum{instance=\"$instance\"}",
     "legendFormat": "{{Tota}}, {{chaincode}}"
    }
   ]
  }
 ]
}