{
 "title": "Robot Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "robot_app_info" } },
   {
    "name": "channel",
    "query": {
     "query": "robot_collector_process_block_num"
    }
   },
   {
    "name": "robot",
    "query": {
     "query": "robot_collector_process_block_num"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Init Duration Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robot_app_init_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "App Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "robot_app_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robot_robot_started_total{instance=~\"$instance\"}",
     "legendFormat": "{{job}} {{robot}}"
    }
   ]
  },
  {
   "title": "Batch Collect Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(robot_batch_collect_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{robot}}"
    }
   ]
  },
  {
   "title": "Batch Size Estimated Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "robot_batch_size_estimated_diff_count{instance=~\"$instance\"}",
     "legendFormat": "{{robot}}"
    }
   ]
  },
  { "title": "Channel info ($channel)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "channel" },
  {
   "title": "Robot Block Tx Count ($channel)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "robot_block_tx_count_count{instance=~\"$instance\",channel=\"$channel\"}",
     "legendFormat": "{{instance}} {{robot}}"
    }
   ]
  },
  {
   "title": "Collector process block num ($channel)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "robot_collector_process_block_num{instance=~\"$instance\",channel=\"$channel\"}",
     "legendFormat": "{{instance}}, robot: {{robot}}"
    }
   ]
  },
  {
   "title": "TX waiting process count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "robot_tx_waiting_process_count{instance=~\"$instance\",channel=~\"$channel\"}",
     "legendFormat": "{{instance}} {{robot}}"
    }
   ]
  }
 ]
}